# Generated by Django 4.2.7 on 2025-08-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='studentmoduleprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentmoduleprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='studentmoduleprogress',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseModule',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.DeleteModel(
            name='StudentModuleProgress',
        ),
    ]
